### ISSUE TITLE
why optimization not working?

### ISSUE THREAD

**Issue by NJUSTzandyz** [webis-de/arxiv23-prompt-embedding-manipulation#3]
It's an amazing method!
but when I try to use the optimization(increase_aesthetic_score & increase_sharpness) from your code, it's not working, and sharpness values vary from 5.14 to 5.11 with 50 iterations, do I need to do any other settings?

**Comment by niklasdeckers** [comment]
Thanks for your remark! Based on the additional info that you provided, we now added a loss scale parameter that you can modify to increase the intensity of the adjustment: https://github.com/webis-de/arxiv23-prompt-embedding-manipulation/blob/8e41100c1fb358a28aa838b0b128380ab5a0cc10/metric_based_optimization/full_pipeline_descent.py#L206

You might want to try values of ca. 50 to see results more quickly.
Please note that the required factor might also depend on the seed that is used.

The loss scale is used as a factor within the loss, which has a direct proportional effect on the gradient. It seems like this can not be represented within the learning rate (as it would with SGD, see https://stackoverflow.com/a/56861721 ). With Adam, the optimization would be invariant of the loss scale; however, we use the Lion optimizer here.
